# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RGlzd6Mo8s9W-kSJohmKd-EiTfZoerwm
"""

from setuptools import setup, find_packages

setup(
    name='load_sec2',
    version='0.1',
    packages=find_packages()
)