# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QhcSvGcGWnoH-oYB0uNwaY_82oq6WEQN
"""

from load_sec2.load_sec2 import *