# -*- coding: utf-8 -*-
"""load_sec2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/120sOtEub61Qu9mofqUeM-EA57tcgoWj1
"""

def load(name):
    f = open(name, 'r', encoding="shift-jis")

    data = f.read()
    print(data)

    f.close()

name = "ahen.txt"
load(name)

